#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

obj-$(CONFIG_DRM_IVIP) += ivip.o
ivip-objs := intel_vip_drv.o intel_vip_conn.o
